Mike
KiMe212/rps-game pull request #1
Opened 2023-03-27 20:58 UTC by KiMe212

Где должен быть .gitignor?

2023-03-28 07:47 UTC, Vladgasik requested changes
Rename file to `.gitignore`
Move that file to root directory

2023-03-28 21:07 UTC, KiMe212 commented
Maybe understood you

2023-03-28 21:10 UTC, KiMe212 commented
Ok, i not sure that make so it, but work

2023-03-28 22:51 UTC, Vladgasik requested changes
Also, add `__pycache__/` to .gitignore

2023-03-31 15:04 UTC, KiMe212 commented
Check on `routes.py` if you have free time. Am I rigth return models?

2023-04-05 16:09 UTC, KiMe212 commented
I have problems with `Enum`(I don't now where and how use it), `pyest`(prodlem with `post_test`), `pre-commit`(`isort` work unclear)

2023-04-06 15:19 UTC, Vladgasik commented on .pre-commit-config.yaml
> +#-   repo: https://github.com/PyCQA/isort
Правильно понимаю, что black и isort подружить не смог?)

2023-04-06 15:19 UTC, Vladgasik commented on app/routes.py
> +    pc_choice = random.choice(config.CHOICSE_LIST)
`CHOICE_LIST`*

2023-04-06 15:21 UTC, Vladgasik commented on app/schemas.py
> +from .settings import config
Не делай такие импорты, потому что не сразу понятно откуда ты импортишь и мне пришлось смотреть в какой директории текущий файл
Делай `from app.settings`

Чуть побольше погугли про absolute vs relative path

2023-04-06 15:23 UTC, Vladgasik commented on test/conftest.py
> +    return clin
Ты старался, но просто
```
@pytest.fixture
def client():
    return TestClient(app)

2023-04-06 15:26 UTC, Vladgasik commented on test/test_get_request.py
> +    [("paper", "Draw"), ("scissors", "You Win"), ("rock", "You Lose")],
Всегда разделяют, чтобы повысить читаемость кода
```
[
    ("paper", "Draw"), 
    ("scissors", "You Win"), 
    ("rock", "You Lose"),
]

2023-04-06 15:26 UTC, Vladgasik commented on test/test_get_request.py
> +    "choices, answer",
В качестве параметра у тебя один choice, а не много choices

2023-04-06 15:28 UTC, Vladgasik commented on test/test_get_request.py
> +    assert response.status_code == 200
Обычно  тесты пишут так

подготовка данных
<пустая строка>
запрос
<пустая строка>
блок assert

2023-04-06 15:29 UTC, Vladgasik commented on app/services.py
> +# def get_winner(choice_first: str, choice_second: str):
В финальной версии чтобы таких комментов я не видел)

2023-04-06 15:30 UTC, Vladgasik commented on .pytest_cache/CACHEDIR.TAG
Снеси эти файлы и обнови `.gitignore` на вот такой
https://github.com/github/gitignore/blob/main/Python.gitignore

2023-04-06 15:31 UTC, Vladgasik commented on test/get_message_from_game_result.py
> +from app.services import get_message_from_game_result
ну и папку с тестами во множественном числе пожалуйста

2023-04-06 15:33 UTC, Vladgasik commented on test/get_message_from_game_result.py
> +    assert get_message_from_game_result("paper", "rock") == "You Win"
Думаю сам понимаешь, что копипаст это плохо)
Сделай через параметры
user_choice, pc_choice, message

2023-04-06 15:38 UTC, Vladgasik commented on app/routes.py
> +@router.post("/rps", response_model=ChoiceModel, status_code=status.HTTP_200_OK)
```
@router_post(
    path="/rps",
    status_code=status.HTTP_200_OK,
    response_model=ChoiceModel,
)
```
Если заметил, то я всегда ставлю запятую перед скобкой
Это чтобы когда кто-то добавит еще одну строку после твоей ему не приходилось дописывать эту запятую
И если он поставит запятую, то `git` будет показывать, что он удалил твою строку и добавил свою, а это лишняя информация

2023-04-06 15:38 UTC, Vladgasik commented on pyproject.toml
> +pre-commit = "^3.2.2"
куда бы перенести пре-коммит? хммм

2023-04-06 15:52 UTC, Vladgasik commented on docs/API.md
> +curl -XPOST "http://localhost:8000/game" -d '{"path":"/rps","httpMethod":"GET","version":"1.0","requestContext":{"protocol":"HTTP/1.1"}, "queryStringParameters": {"choice": "paper"}, "body": null}'
Либо раздели GET и POST, либо в скобках возле Body-params напиши POST, а у URL-params - GET
Глянь про curl один видосик какой-нибудь
```
curl http://localhost:8000/game/rps?choice=paper

curl -x POST http://localhost:8000/game/rps -d '{"choice": "paper"}'

2023-04-06 15:54 UTC, Vladgasik commented on docs/API.md
>  **Content**: {detail: "You have incorrect choice"}
`"detail"`*

2023-04-06 15:56 UTC, Vladgasik commented on docs/RUN.md
> +    Path ``C:\Users\AppData\Local\pypoetry\Cache\virtualenvs\(your project)\Scripts\python``
Тут обычно пишут как запустить проект, а не как сделать его с нуля и начать разрабатывать

а запускается он 
```
curl -sSL https://install.python-poetry.org | python3 -

# В корневой папке
poetry install
poetry run uvicorn app.main:app --reload

2023-04-06 15:57 UTC, Vladgasik commented on app/settings.py
> +    DESCRIPTION: str = "None"
Что-то я не вижу, чтобы ты использовал DESCRIPTION и VERSION

2023-04-06 15:57 UTC, Vladgasik commented on app/settings.py
> +        env_file = ".env"
Ты это не используешь, так что снеси

2023-04-06 15:59 UTC, Vladgasik commented on app/services.py
> +def get_message_from_game_result(first_choice, second_choice):
`Создай свой enum GameResult и вместо get_winner сделай get_message_from_game_result & get_game_result
 Также добавь тесты для get_response_message и get_game_result`

2023-04-06 16:04 UTC, Vladgasik commented on app/settings.py
> +    CHOICSE_LIST: list = ("rock", "paper", "scissors")
`: tuple[str]`

2023-04-08 09:56 UTC, Vladgasik commented on app/services.py
> +        return GameResult.WIN.value
Возвращай просто `GameResult.WIN`

2023-04-08 09:57 UTC, Vladgasik commented on app/services.py
> +def get_message_from_game_result(first_choice, second_choice):
эта функция будет принимать 1 параметр `game_result: GameResult`

2023-04-08 09:58 UTC, Vladgasik commented on pyproject.toml
> +fastapi = {extras = ["all"], version = "^0.95.0"}
напиши просто ^0.95.0)

2023-04-08 10:02 UTC, Vladgasik commented on app/routes.py
> +    winner = get_message_from_game_result(
тут будет 2 функции
```
game_result = get_game_result(first, second)
message = get_message_from_game_result(game_result)

2023-04-08 10:03 UTC, Vladgasik commented on app/.gitignore
> +# Byte-compiled / optimized / DLL files
Этот файл лежит в корневой директории, а не в app/

2023-04-08 10:04 UTC, Vladgasik requested changes
Последние изменения

2023-04-08 10:16 UTC, KiMe212 commented on app/services.py
> +def get_message_from_game_result(first_choice, second_choice):
А где мне тогда выводить ответ с комбинаций?

2023-04-08 14:41 UTC, Vladgasik commented on app/settings.py
> +    LOSE_COMBINATIONS: list[tuple] = {
WIN 
`tuple[tuple[str, ...]]`
LOSS*
У тебя тут вообще `set[tuple[str, ...]]`, но сделай так же как и WIN

2023-04-08 14:45 UTC, Vladgasik commented on app/schemas.py
> +    TIE = "Tie"
Все-таки давай заменим здесь на auto(), представим, что этот GameResult нам удобно хранить в БД в виде int-а 
auto импортируй из enum
ну и соответственно в get_message_from_game_result
```
GAME_RESULT_TO_MSG = {GameResult.WIN: "You win", ...}
```
    
```suggestion
class GameResult(Enum):
    WIN = auto()  # 1
    LOSS = auto()
    TIE = auto()
```

2023-04-08 14:48 UTC, Vladgasik commented on .pre-commit-config.yaml
> +-   repo: https://github.com/charliermarsh/ruff-pre-commit
Давай еще такое добавим (прогони все файлы через него)
```suggestion
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -  id: trailing-whitespace
    -  id: end-of-file-fixer
-   repo: https://github.com/charliermarsh/ruff-pre-commit
```

2023-04-08 19:59 UTC, Vladgasik approved these changes

2023-04-08 20:03 UTC, merged